// THIS IS A GENERATED FILE
// CONTAINS POKEMON-NAMES THAT MIGHT NOT BE IN COBBLEMON
//
// GENERATED USING https://pokeapi.co
//             SEE https://pokeapi.co/docs/graphql

package com.peeteer.cobblemondetector.client.util;

public class PokemonLists {

    // all legendaries
    public static final String[] legendaries = {
        "articuno",
        "zapdos",
        "moltres",
        "mewtwo",
        "raikou",
        "entei",
        "suicune",
        "lugia",
        "ho-oh",
        "regirock",
        "regice",
        "registeel",
        "latias",
        "latios",
        "kyogre",
        "groudon",
        "rayquaza",
        "uxie",
        "mesprit",
        "azelf",
        "dialga",
        "palkia",
        "heatran",
        "regigigas",
        "giratina",
        "cresselia",
        "cobalion",
        "terrakion",
        "virizion",
        "tornadus",
        "thundurus",
        "reshiram",
        "zekrom",
        "landorus",
        "kyurem",
        "xerneas",
        "yveltal",
        "zygarde",
        "type-null",
        "tapu-koko",
        "tapu-lele",
        "tapu-bulu",
        "tapu-fini",
        "cosmog",
        "necrozma",
        "silvally",
        "cosmoem",
        "solgaleo",
        "lunala",
        "zacian",
        "zamazenta",
        "eternatus",
        "kubfu",
        "regieleki",
        "regidrago",
        "glastrier",
        "spectrier",
        "calyrex",
        "enamorus",
        "urshifu",
        "wo-chien",
        "chien-pao",
        "ting-lu",
        "chi-yu",
        "koraidon",
        "miraidon",
        "okidogi",
        "munkidori",
        "fezandipiti",
        "ogerpon",
        "terapagos",
    };

    // apparently mythics and legendaries need to be separate
    public static final String[] mythics = {
        "mew",
        "celebi",
        "jirachi",
        "deoxys",
        "phione",
        "manaphy",
        "darkrai",
        "shaymin",
        "arceus",
        "victini",
        "keldeo",
        "meloetta",
        "genesect",
        "diancie",
        "hoopa",
        "volcanion",
        "magearna",
        "marshadow",
        "zeraora",
        "meltan",
        "melmetal",
        "zarude",
        "pecharunt",
    };

    // all starter pokemon plus their evolutions
    public static final String[] starter = {
        "bulbasaur",
        "ivysaur",
        "venusaur",
        "chikorita",
        "bayleef",
        "meganium",
        "treecko",
        "grovyle",
        "sceptile",
        "turtwig",
        "grotle",
        "torterra",
        "snivy",
        "servine",
        "serperior",
        "chespin",
        "quilladin",
        "chesnaught",
        "rowlet",
        "dartrix",
        "decidueye",
        "grookey",
        "thwackey",
        "rillaboom",
        "sprigatito",
        "floragato",
        "meowscarada",
        "squirtle",
        "wartortle",
        "blastoise",
        "totodile",
        "croconaw",
        "feraligatr",
        "mudkip",
        "marshtomp",
        "swampert",
        "piplup",
        "prinplup",
        "empoleon",
        "oshawott",
        "dewott",
        "samurott",
        "froakie",
        "frogadier",
        "greninja",
        "popplio",
        "brionne",
        "primarina",
        "sobble",
        "drizzile",
        "inteleon",
        "quaxly",
        "quaxwell",
        "quaquaval",
        "charmander",
        "charmeleon",
        "charizard",
        "cyndaquil",
        "quilava",
        "typhlosion",
        "torchic",
        "combusken",
        "blaziken",
        "chimchar",
        "monferno",
        "infernape",
        "tepig",
        "pignite",
        "emboar",
        "fennekin",
        "braixen",
        "delphox",
        "litten",
        "torracat",
        "incineroar",
        "scorbunny",
        "raboot",
        "cinderace",
        "fuecoco",
        "crocalor",
        "skeledirge",
    };

    // all baby pokemon without their evolutions
    public static final String[] babies = {
        "pichu",
        "cleffa",
        "igglybuff",
        "togepi",
        "tyrogue",
        "smoochum",
        "elekid",
        "magby",
        "azurill",
        "wynaut",
        "budew",
        "chingling",
        "bonsly",
        "mime-jr",
        "happiny",
        "munchlax",
        "riolu",
        "mantyke",
        "toxel",
    };

    // all ultra-beasts
    public static final String[] ultra_beasts = {
        "nihilego",
        "buzzwole",
        "pheromosa",
        "xurkitree",
        "celesteela",
        "kartana",
        "guzzlord",
        "poipole",
        "naganadel",
        "stakataka",
        "blacephalon",
    };

    // all paradox mons
    public static final String[] paradox_mons = {
        "greattusk",
        "screamtail",
        "brutebonnet",
        "fluttermane",
        "slitherwing",
        "sandyshocks",
        "roaringmoon",
        "walkingwake",
        "gougingfire",
        "ragingbolt",
        "irontreads",
        "ironbundle",
        "ironhands",
        "ironjugulis",
        "ironmoth",
        "ironthorns",
        "ironvaliant",
        "ironleaves",
        "ironboulder",
        "ironcrown",
        "koraidon",
        "miraidon",
    };
}
